id: P0E3FE520
initial_creation_type: input
source_metadata:
  Title: Bauddhalaghugrangtha-sangraha
  Editor: Pandey, Janardan
  Publisher: Central Institute of Higher Tibetan Studies,
  Place of Publication: Sarnath
  Year: '1997'
  Kriyāsaṃgrahakārikā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:52:14.882362'
last_modified_at: '2022-03-08T16:52:14.882370'
